### ISSUE TITLE
CLI: AssertionError: ADDRESS is not a tuple (list)

### ISSUE THREAD

**Issue by pahaz** [pahaz/sshtunnel#13]
testssh> python -m sshtunnel -U vagrant -P vagrant -L :3306 -R 127.0.0.1:3306 -p 2222 localhost
    2015-06-18 00:44:34,637 | WARNING | Could not read SSH configuration file: ~/.ssh/config
    Traceback (most recent call last):
      File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Python34\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\pahaz_000\Downloads\!_rm\sshpahaz\sshtunnel.py", line 993, in <module>
        with open_tunnel(**vars(ARGS)) as my_tunnel:
      File "C:\Users\pahaz_000\Downloads\!_rm\sshpahaz\sshtunnel.py", line 883, in open_tunnel
        forwarder = SSHTunnelForwarder(ssh_address, **kwargs)
      File "C:\Users\pahaz_000\Downloads\!_rm\sshpahaz\sshtunnel.py", line 586, in __init__
        check_addresses(remote_bind_addresses)
      File "C:\Users\pahaz_000\Downloads\!_rm\sshpahaz\sshtunnel.py", line 166, in check_addresses
        check_address(address)
      File "C:\Users\pahaz_000\Downloads\!_rm\sshpahaz\sshtunnel.py", line 153, in check_address
        .format(type(address).__name__)
    AssertionError: ADDRESS is not a tuple (list)

**Comment by pahaz** [comment]
https://github.com/pahaz/sshtunnel/commit/40fef023d680bb15453651027bb2cdc913cd2db1#diff-76bc1662a114401c2954deb92b740081L954 
https://github.com/pahaz/sshtunnel/commit/40fef023d680bb15453651027bb2cdc913cd2db1#diff-76bc1662a114401c2954deb92b740081L962

Fixed!
