### ISSUE TITLE
SSH Protocol Error when using Netmiko/Paramiko

### ISSUE THREAD

**Issue by Phxntxm** [pahaz/sshtunnel#148]
I'm using pretty much example 2, and my code is here:
```
import paramiko
from sshtunnel import SSHTunnelForwarder, create_logger

with SSHTunnelForwarder(
    ("jumphost", 22),
    ssh_username="jumphostusername",
    ssh_password="jumphostpassword",
    remote_bind_address=("endhost", 22),
    local_bind_address=('0.0.0.0', 10022),
    logger=create_logger(loglevel=1)
) as tunnel:
    client = paramiko.SSHClient()
    client.load_system_host_keys()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect('127.0.0.1', 10022, username="endhostuser", password="endhostpassword")
    # do some operations with client session
    client.close()

print('FINISH!')
```

This doesn't work, and gives this output:
```
2019-04-29 17:38:11,393| INF | MainThrea/0993@sshtunnel | 0 keys loaded from agent
2019-04-29 17:38:11,393| INF | MainThrea/1042@sshtunnel | 0 keys loaded from host directory
2019-04-29 17:38:11,393| INF | MainThrea/0914@sshtunnel | Connecting to gateway: jumphost:22 as user 'jumphostuser'
2019-04-29 17:38:11,393| DEB | MainThrea/0917@sshtunnel | Concurrent connections allowed: True
2019-04-29 17:38:11,393| DEB | MainThrea/1369@sshtunnel | Trying to log in with password: ************
2019-04-29 17:38:16,469| INF | Srv-10022/1389@sshtunnel | Opening tunnel: 0.0.0.0:10022 <> endhost:22
2019-04-29 17:38:17,595| TRA |  Thread-3/0349@sshtunnel | #1 <-- ('127.0.0.1', 60579) to ('endhost', 22) was rejected by the SSH server
2019-04-29 17:38:17,595| ERR |  Thread-3/0385@sshtunnel | Could not establish connection from ('127.0.0.1', 10022) to remote side of the tunnel
2019-04-29 17:38:17,596| ERR |  Thread-4/1746@transport | Exception: Error reading SSH protocol banner
2019-04-29 17:38:17,598| ERR |  Thread-4/1744@transport | Traceback (most recent call last):
2019-04-29 17:38:17,598| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
2019-04-29 17:38:17,598| ERR |  Thread-4/1744@transport |     buf = self.packetizer.readline(timeout)
2019-04-29 17:38:17,598| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport |     buf += self._read_timeout(timeout)
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport |     raise EOFError()
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport | EOFError
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport | 
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport | During handling of the above exception, another exception occurred:
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport | 
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport | Traceback (most recent call last):
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
2019-04-29 17:38:17,599| ERR |  Thread-4/1744@transport |     self._check_banner()
2019-04-29 17:38:17,600| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
2019-04-29 17:38:17,600| ERR |  Thread-4/1744@transport |     "Error reading SSH protocol banner" + str(e)
2019-04-29 17:38:17,600| ERR |  Thread-4/1744@transport | paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2019-04-29 17:38:17,600| ERR |  Thread-4/1744@transport | 
2019-04-29 17:38:17,600| INF | MainThrea/1408@sshtunnel | Shutting down tunnel ('0.0.0.0', 10022)
2019-04-29 17:38:17,695| INF | Srv-10022/1395@sshtunnel | Tunnel: 0.0.0.0:10022 <> endhost:22 released
2019-04-29 17:38:17,696| DEB | MainThrea/1422@sshtunnel | Transport is closed
Traceback (most recent call last):
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.connect('127.0.0.1', 10022, username="endhostuser", password="endhostpassword")
  File ".../.python/lib/python3.6/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

Running this worked just fine however
```
sshtunnel jumphost -U jumphostuser -P jumphostpassword -L 127.0.0.1:10022 -R endhost:22
```

Looks maybe similar to #109 however there's been no updated for over a year, so I'm posting this here
```
Name: sshtunnel
Version: 0.1.4
Name: paramiko
Version: 2.4.2
Endhost: iOS device
Jumphost: Scientific linux 6.7
```

**Comment by fernandezcuesta** [comment]
Hi, thanks for the detailed report.
As far as I know, the difference between calling from CLI and your snippet is that the former uses `open_tunnel()` wrapper instead. The main difference is that by default the local tunnel check is disabled.
Could you please check again using the wrapper `open_tunnel()` instead of `SSHTunnelForwarder()`?

**Comment by Phxntxm** [comment]
I tried replacing `SSHTunnelForwarder` with `open_tunnel` and the same error happened....just in case there's a small difference I don't see, the response for a literal drop and replace for the above is below:

```
2019-04-30 18:16:15,850| INF | MainThrea/0993@sshtunnel | 0 keys loaded from agent
2019-04-30 18:16:15,850| INF | MainThrea/1042@sshtunnel | 0 keys loaded from host directory
2019-04-30 18:16:15,850| INF | MainThrea/0914@sshtunnel | Connecting to gateway: jumphost:22 as user 'jumphostuser'
2019-04-30 18:16:15,850| DEB | MainThrea/0917@sshtunnel | Concurrent connections allowed: True
2019-04-30 18:16:15,851| DEB | MainThrea/1369@sshtunnel | Trying to log in with password: ************
2019-04-30 18:16:22,800| INF | Srv-10022/1389@sshtunnel | Opening tunnel: 0.0.0.0:10022 <> endhost:22
2019-04-30 18:16:23,931| TRA |  Thread-3/0349@sshtunnel | #1 <-- ('127.0.0.1', 60035) to ('endhost', 22) was rejected by the SSH server
2019-04-30 18:16:23,931| ERR |  Thread-3/0385@sshtunnel | Could not establish connection from ('127.0.0.1', 10022) to remote side of the tunnel
2019-04-30 18:16:23,932| ERR |  Thread-4/1746@transport | Exception: Error reading SSH protocol banner
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport | Traceback (most recent call last):
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |     buf = self.packetizer.readline(timeout)
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |     buf += self._read_timeout(timeout)
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport |     raise EOFError()
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport | EOFError
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport | 
2019-04-30 18:16:23,934| ERR |  Thread-4/1744@transport | During handling of the above exception, another exception occurred:
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport | 
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport | Traceback (most recent call last):
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport |     self._check_banner()
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport |   File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport |     "Error reading SSH protocol banner" + str(e)
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport | paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2019-04-30 18:16:23,935| ERR |  Thread-4/1744@transport | 
2019-04-30 18:16:23,936| INF | MainThrea/1408@sshtunnel | Shutting down tunnel ('0.0.0.0', 10022)
2019-04-30 18:16:24,030| INF | Srv-10022/1395@sshtunnel | Tunnel: 0.0.0.0:10022 <> endhost:22 released
2019-04-30 18:16:24,031| DEB | MainThrea/1422@sshtunnel | Transport is closed
Traceback (most recent call last):
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.connect('127.0.0.1', 10022, username="endhostuser", password="endhostpassword")
  File ".../.python/lib/python3.6/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File ".../.python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Comment by Phxntxm** [comment]
So just an update on this, this was my mistake upon testing this....but the CLI method doesn't work. The tunnel opens just fine, but paramiko just can't seem to use it no matter what I do. I'm still not certain, does this mean this is a Paramiko bug? I can SSH through that tunnel perfectly fine manually
