### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by suckmypython** [pahaz/sshtunnel#166]
Hello, I have a mysql connection that I use with a sshtunnel.SSHTunnelForwarder. For some reason when I do anything with the cursor I get the below error. But, I however can do conn.get_server_info() just fine. 

I know it's not the sql server because if I make a ssh tunnel manually from cmd and the code runs fine.  

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/network.py", line 249, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
ConnectionResetError: [Errno 104] Connection reset by peer`

`Traceback (most recent call last):
  File "test_file.py", line 15, in <module>
    user_info = conn.get_user_id_and_user_name("123456")
  File "/home/pi/scripts/rfid_package/sql.py", line 69, in get_user_id_and_user_name
    self.cursor.execute(sql, (rfid_number,))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 590, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 350, in _send_cmd
    return self._socket.recv()
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/network.py", line 278, in recv_plain
    errno=2055, values=(self.get_address(), _strioerror(err)))
mysql.connector.errors.OperationalError: 2055: Lost connection to MySQL server at '0.0.0.0:3306', system error: 104 Connection reset by peer`

**Comment by suckmypython** [comment]
structured the code differently and it worked.
