### ISSUE TITLE
pip3 install sshtunnel on Fedora

### ISSUE THREAD

**Issue by federicozanini** [pahaz/sshtunnel#179]
Hi,
when I do pip3 install sshtunnel on my Fedora31 I get the following error:

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cf_emmbs/sshtunnel/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cf_emmbs/sshtunnel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-98qrjgt1
         cwd: /tmp/pip-install-cf_emmbs/sshtunnel/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cf_emmbs/sshtunnel/setup.py", line 14, in <module>
        from setuptools.command.test import test as TestCommand
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/test.py", line 18, in <module>
        from .build_py import _unique_everseen
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_py.py", line 16, in <module>
        from setuptools.lib2to3_ex import Mixin2to3
      File "/usr/local/lib/python3.7/site-packages/setuptools/lib2to3_ex.py", line 12, in <module>
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package
      File "/usr/lib64/python3.7/lib2to3/refactor.py", line 26, in <module>
        from .fixer_util import find_root
      File "/usr/lib64/python3.7/lib2to3/fixer_util.py", line 7, in <module>
        from .pygram import python_symbols as syms
      File "/usr/lib64/python3.7/lib2to3/pygram.py", line 32, in <module>
        python_grammar = driver.load_packaged_grammar("lib2to3", _GRAMMAR_FILE)
      File "/usr/lib64/python3.7/lib2to3/pgen2/driver.py", line 156, in load_packaged_grammar
        return load_grammar(grammar_source)
      File "/usr/lib64/python3.7/lib2to3/pgen2/driver.py", line 131, in load_grammar
        g.load(gp)
      File "/usr/lib64/python3.7/lib2to3/pgen2/grammar.py", line 108, in load
        d = pickle.load(f)
    EOFError: Ran out of input
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I have pip3 and setuptools updated at the last version.
Thanks for your help!

**Comment by pahaz** [comment]
It doesn't look like a `sshtunnel` bug. Any updates? 
It looks like a problem with your environment.
I don't know how to help you ...
