### ISSUE TITLE
Add support reconnection of transport.

### ISSUE THREAD

**Issue by pahaz** [pahaz/sshtunnel#20]
Sometimes transport have socker error: PARAMIKO: 1430@transport | Socket exception: An existing connection was forcibly closed by the remote host (10054)
Required add reconnection mechanism for solving this problem.

    2015-07-08 11:01:34,346 | DEBUG   | Incoming request #30
    2015-07-08 11:01:53,002 | DEBUG   | Incoming request #29 connection closed.
    2015-07-08 11:03:18,878 | WARNING | Incoming request #30 sending RST
    2015-07-08 11:03:18,882 | DEBUG   | Incoming request #30 connection closed.
    2015-07-08 11:11:26,091 | ERROR   | PARAMIKO: 1430@transport | Socket exception: An existing connection was forcibly closed by the remote host (10054)
    2015-07-08 11:11:26,094 | DEBUG   | Incoming request #6 connection closed.
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 2446)
    2015-07-08 11:11:26,095 | DEBUG   | Incoming request #28 connection closed.
    Traceback (most recent call last):
    2015-07-08 11:11:26,095 | DEBUG   | Incoming request #27 connection closed.
    2015-07-08 11:11:26,096 | DEBUG   | Incoming request #32 to ('127.0.0.1', 8888) failed: SSHException('Unable to open channel.',)
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
    ----------------------------------------
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
    Exception happened during processing of request from ('127.0.0.1', 2447)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 731, in open_channel
        raise e
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 731, in open_channel
        raise e
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 1592, in run
        ptype, m = self.packetizer.read_message()
    paramiko.ssh_exception.SSHException: Unable to open channel.
      File "C:\Python34\lib\site-packages\paramiko\packet.py", line 341, in read_message
        header = self.read_all(self.__block_size_in, check_rekey=True)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\paramiko\packet.py", line 204, in read_all
        x = self.__socket.recv(n)
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
    ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
    ----------------------------------------
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 252, in handle
        raise HandlerSSHTunnelForwarderError(msg)
    HandlerSSHTunnelForwarderError: Incoming request #32 to ('127.0.0.1', 8888) failed: SSHException('Unable to open channel.',)
    ----------------------------------------
    2015-07-08 11:11:27,122 | DEBUG   | Incoming request #33 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 2453)
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 696, in open_channel
        raise SSHException('SSH session not active')
    paramiko.ssh_exception.SSHException: SSH session not active

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 252, in handle
        raise HandlerSSHTunnelForwarderError(msg)
    HandlerSSHTunnelForwarderError: Incoming request #33 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    2015-07-08 11:11:28,181 | DEBUG   | Incoming request #34 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 2455)
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 696, in open_channel
        raise SSHException('SSH session not active')
    paramiko.ssh_exception.SSHException: SSH session not active

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 252, in handle
        raise HandlerSSHTunnelForwarderError(msg)
    HandlerSSHTunnelForwarderError: Incoming request #34 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    2015-07-08 11:11:29,275 | DEBUG   | Incoming request #35 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 2457)
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 696, in open_channel
        raise SSHException('SSH session not active')
    paramiko.ssh_exception.SSHException: SSH session not active

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 252, in handle
        raise HandlerSSHTunnelForwarderError(msg)
    HandlerSSHTunnelForwarderError: Incoming request #35 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    2015-07-08 11:11:30,336 | DEBUG   | Incoming request #36 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 2459)
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 242, in handle
        self.request.getpeername())
      File "C:\Python34\lib\site-packages\paramiko\transport.py", line 696, in open_channel
        raise SSHException('SSH session not active')
    paramiko.ssh_exception.SSHException: SSH session not active

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\socketserver.py", line 617, in process_request_thread
        self.finish_request(request, client_address)
      File "C:\Python34\lib\socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "C:\Python34\lib\socketserver.py", line 673, in __init__
        self.handle()
      File "C:\Python34\lib\site-packages\sshtunnel.py", line 252, in handle
        raise HandlerSSHTunnelForwarderError(msg)
    HandlerSSHTunnelForwarderError: Incoming request #36 to ('127.0.0.1', 8888) failed: SSHException('SSH session not active',)

**Comment by pahaz** [comment]
Is not actual ... closed by timeout
