### ISSUE TITLE
tunnel connections using a key stopped working

### ISSUE THREAD

**Issue by 0x7162** [pahaz/sshtunnel#230]
I'm putting a quick description as it could be a duplicate of #226 or something else.

I'm using a setup:
    ServerA (auth using private key)
    ServerB (auth using the same private key)
    
 My host -> ServerA -> ServerB
 
 Once I'm getting a local port to connect (like `127.0.0.1:44321`), it gives me an error:
 ```
 ssh user@127.0.0.1 -p 44321 -i key.pem
 ...
 Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
 ```
 
 though:
 ```
 ssh -i key.pem user@hostB -o "proxycommand ssh -W %h:%p -i key.pem user@hostA"
 ```
 works fine

**Comment by 0x7162** [comment]
Initially it looked similar to:
https://github.com/paramiko/paramiko/issues/1590
https://github.com/paramiko/paramiko/issues/1606

and it could apply to sshtunnel as well

**Comment by 0x7162** [comment]
```
2021-02-05T07:38:01: %PARAMIKO-DEBUG: [chan 17] EOF sent (17)
2021-02-05T07:38:01: %FAST-DEBUG: starting thread (client mode): 0x4730a30
2021-02-05T07:38:01: %PARAMIKO-DEBUG: [chan 18] Max packet in: 32768 bytes
2021-02-05T07:38:01: %FAST-DEBUG: Local version/idstring: SSH-2.0-paramiko_2.7.2
2021-02-05T07:38:01: %PARAMIKO-DEBUG: [chan 17] EOF received (17)
2021-02-05T07:38:01: %PARAMIKO-DEBUG: [chan 18] Max packet out: 32768 bytes
2021-02-05T07:38:01: %PARAMIKO-DEBUG: Secsh channel 18 opened.
2021-02-05T07:38:01: %FAST-DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-05T07:38:01: %FAST-INFO: Connected (version 2.0, client OpenSSH_7.4)
2021-02-05T07:38:01: %FAST-DEBUG: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
2021-02-05T07:38:01: %FAST-DEBUG: Kex agreed: curve25519-sha256@libssh.org
2021-02-05T07:38:01: %FAST-DEBUG: HostKey agreed: ssh-ed25519
2021-02-05T07:38:01: %FAST-DEBUG: Cipher agreed: aes128-ctr
2021-02-05T07:38:01: %FAST-DEBUG: MAC agreed: hmac-sha2-256
2021-02-05T07:38:01: %FAST-DEBUG: Compression agreed: zlib@openssh.com
2021-02-05T07:38:01: %FAST-DEBUG: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-05T07:38:01: %FAST-DEBUG: Switch to new keys ...
2021-02-05T07:38:01: %FAST-DEBUG: Trying discovered key b'1a8d0f11b6b84a139b0fdcc777f73ee8' in key.pem
2021-02-05T07:38:01: %FAST-DEBUG: userauth is OK
2021-02-05T07:38:01: %FAST-INFO: Authentication (publickey) failed.
2021-02-05T07:38:01: %FAST-DEBUG: Trying discovered key b'cf70f957167cbc5b5df5fb04a64dbcbd' in key.pem
2021-02-05T07:38:01: %FAST-DEBUG: userauth is OK
2021-02-05T07:38:01: %FAST-ERROR: Unknown exception: q must be exactly 160, 224, or 256 bits long
2021-02-05T07:38:01: %FAST-ERROR: Traceback (most recent call last):
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2109, in run
2021-02-05T07:38:01: %FAST-ERROR:     handler(self.auth_handler, m)
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
2021-02-05T07:38:01: %FAST-ERROR:     sig = self.private_key.sign_ssh_data(blob)
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
2021-02-05T07:38:01: %FAST-ERROR:     key = dsa.DSAPrivateNumbers(
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 250, in private_key
2021-02-05T07:38:01: %FAST-ERROR:     return backend.load_dsa_private_numbers(self)
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 852, in load_dsa_private_numbers
2021-02-05T07:38:01: %FAST-ERROR:     dsa._check_dsa_private_numbers(numbers)
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 147, in _check_dsa_private_numbers
2021-02-05T07:38:01: %FAST-ERROR:     _check_dsa_parameters(parameters)
2021-02-05T07:38:01: %FAST-ERROR:   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 139, in _check_dsa_parameters
2021-02-05T07:38:01: %FAST-ERROR:     raise ValueError("q must be exactly 160, 224, or 256 bits long")
2021-02-05T07:38:01: %FAST-ERROR: ValueError: q must be exactly 160, 224, or 256 bits long
```
