### ISSUE TITLE
If debug_level argument is passed to constructor then unknown argument error is raised

### ISSUE THREAD

**Issue by nelsonw2014** [pahaz/sshtunnel#27]
```python
SSHTunnelForwarder( '1.2.3.4', 22, debug_level='ERROR')
```
Results in an error (similar to this):
```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/pyenvs/application/__main__.py", line 213, in <module>
    args.profile
  File "/Users/user/pyenvs/application/ssh_tools/ssh.py", line 47, in forward_necessary_ports
    debug_level='ERROR'
  File "/usr/local/lib/python3.4/site-packages/sshtunnel.py", line 552, in __init__
    raise ValueError('Unknown arguments {0:!r}'.format(kwargs))
TypeError: non-empty format string passed to object.__format__
```
debug_error is a configurable kwarg so this shouldn't be the case. A pop occurring after the argument is read should occur

**Comment by nelsonw2014** [comment]
I read the code incorrectly. Ignore this issue
