### ISSUE TITLE
Test coverage error

### ISSUE THREAD

**Issue by fernandezcuesta** [pahaz/sshtunnel#63]
The following error is shown during tests:

    INTERNALERROR> AssertionError: Test coverage should never be `None`

Full log:
```
GLOB sdist-make: /data/virtualenv/sshtunnel/sshtunnel/setup.py
py27 inst-nodeps: /data/virtualenv/sshtunnel/sshtunnel/.tox/dist/sshtunnel-0.0.8.3.zip
py27 installed: apipkg==1.4,cffi==1.7.0,coverage==4.1,cryptography==1.4,enum34==1.1.6,execnet==1.4.1,funcsigs==1.0.2,idna==2.1,ipaddress==1.0.16,mock==2.0.0,paramiko==2.0.1,pbr==1.10.0,py==1.4.31,pyasn1==0.1.9,pycparser==2.14,pytest==2.9.2,pytest-cov==2.3.0,pytest-xdist==1.14,six==1.10.0,sshtunnel==0.0.8.3
py27 runtests: PYTHONHASHSEED='2974953662'
py27 runtests: commands[0] | python -V
Python 2.7.12
py27 runtests: commands[1] | py.test --showlocals --cov sshtunnel --durations=10 -n4 tests
================================================= test session starts =================================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /data/virtualenv/sshtunnel/sshtunnel, inifile:
plugins: cov-2.3.0, xdist-1.14
gw0 [44] / gw1 [44] / gw2 [44] / gw3 [44]
scheduling tests via LoadScheduling
......................................X....INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/pytest_cov/plugin.py", line 221, in pytest_runtestloop
INTERNALERROR>     assert self.cov_total is not None, 'Test coverage should never be `None`'
INTERNALERROR> AssertionError: Test coverage should never be `None`
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/data/virtualenv/sshtunnel/sshtunnel/.tox/py27/lib/python2.7/site-packages/pytest_cov/plugin.py", line 221, in pytest_runtestloop
INTERNALERROR>     assert self.cov_total is not None, 'Test coverage should never be `None`'
INTERNALERROR> AssertionError: Test coverage should never be `None`
.Coverage.py warning: Module sshtunnel was never imported.
Coverage.py warning: No data was collected.
```

**Comment by fernandezcuesta** [comment]
Related to https://github.com/pytest-dev/pytest-cov/issues/124

**Comment by fernandezcuesta** [comment]
Fixed with py.test 2.3.1
