### ISSUE TITLE
Troubleshooting question

### ISSUE THREAD

**Issue by StnadardUsre** [pahaz/sshtunnel#81]
Doesn't work!

**Comment by fernandezcuesta** [comment]
Could you please elaborate (a minimal explanation of what you're doing, output and the expected outcome would do).

**Comment by StnadardUsre** [comment]
Tried dynamic port forwarding example provided in Usage examples: (login credentials are working)
`
from sshtunnel import SSHTunnelForwarder

server = SSHTunnelForwarder(
    '206.214.7.240',
    ssh_username="admin",
    ssh_password="admin",
    remote_bind_address=('127.0.0.1', 8080)
)

server.start()
`
then tried setting various browsers socks5 proxy to 127.0.0.1:8080 and expected the traffic to be tunneled, but it just doesn't work. Tested on Win 7, various Linux distros, Python 3.4 & 3.5. Am I doing something wrong?

**Comment by fernandezcuesta** [comment]
Well you're missing here the fact that a *remote* port is mapped to a random local one. Please retry after adding `local_bind_address=('127.0.0.1', 8080)`.

**Comment by StnadardUsre** [comment]
Yes,  tried with both randomly and explicitly assigned local bind addresses, unfortunately just getting:
```
Could not establish connection from 127.0.0.1, 8080 to remote side of the tunnel
Secsh channel 0 open failed : Connect failed
Secsh channel 1 open failed : Connect failed
Secsh channel 2 open failed : Connect failed
...
```
Is there anything else I can try? As mentioned, tried with multiple SSHs, which surely work in PuTTY, Plink, Bitvise SSH tunnel, etc.

**Comment by fernandezcuesta** [comment]
You may have a look at the logs with loglevel set to DEBUG

**Comment by StnadardUsre** [comment]
Hm, debug trace isn't extremely informative too:
```
DEBUG:paramiko.transport:starting thread (client mode): 0x3b981d0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-dropbear_2013.62
INFO:paramiko.transport:Connected (version 2.0, client dropbear_2013.62)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group1-sha1', 'diffie-hellman-group14-sha1', 'kexguess2@matt.ucc.asn.au'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', '3des-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', '3des-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Attempting password auth...
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
ERROR:paramiko.transport:Secsh channel 0 open FAILED: : Connect failed
ERROR:sshtunnel.SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 8080) to remote side of the tunnel
DEBUG:paramiko.transport:[chan 1] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 2] Max packet in: 32768 bytes
ERROR:paramiko.transport:Secsh channel 1 open FAILED: : Connect failed
ERROR:sshtunnel.SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 8080) to remote side of the tunnel
ERROR:paramiko.transport:Secsh channel 2 open FAILED: : Connect failed
ERROR:sshtunnel.SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 8080) to remote side of the tunnel
```

**Comment by fernandezcuesta** [comment]
Well at least the SSH transport is up, but the tunnel fails to open. I tried the same code snippet as above and I'm having no issues at all. Please doublecheck you don't have port TCP/8080 in use.

**Comment by StnadardUsre** [comment]
Tried on multiple ports, OS, machines, internet providers, Python versions, SSH logins, always getting
`Secsh channel 0 open FAILED: : Connect failed`
Anyway, many thanks for help!

**Comment by pahaz** [comment]
Please use code with extra logging (your pasted logs is not produced by this code). And past the results.
```
from sshtunnel import SSHTunnelForwarder, create_logger

server = SSHTunnelForwarder(
    'adtorg.ru',
    ssh_username="...",
    ssh_password="...",
    remote_bind_address=('127.0.0.1', 8080),
    local_bind_address=('127.0.0.1', 8080),
    logger=create_logger(loglevel=1)
)

server.start()
print(server.local_bind_port)  # show assigned local port
```

**Comment by StnadardUsre** [comment]
Getting this:
```
2017-01-16 01:42:49,787| WAR | MainThrea/0954@sshtunnel | Could not read SSH configuration file: ~/.ssh/config
2017-01-16 01:42:49,797| INF | MainThrea/0981@sshtunnel | 0 keys loaded from agent
2017-01-16 01:42:49,807| INF | MainThrea/0901@sshtunnel | Connecting to gateway: 222.159.239.161:22 as user 'admin'
2017-01-16 01:42:49,807| DEB | MainThrea/0904@sshtunnel | Concurrent connections allowed: True
2017-01-16 01:42:49,807| DEB | MainThrea/1298@sshtunnel | Trying to log in with password: *****
2017-01-16 01:42:52,647| INF |  Srv-8080/1318@sshtunnel | Opening tunnel: 127.0.0.1:8080 <> 127.0.0.1:8080
8080
2017-01-16 01:43:00,520| ERR |  Thread-1/1563@transport | Secsh channel 0 open FAILED: Connection refused: Connect failed
2017-01-16 01:43:00,520| TRA |  Thread-3/0344@sshtunnel | #1 <-- ('127.0.0.1', 56742) to ('127.0.0.1', 8080) was rejected by the SSH server
2017-01-16 01:43:00,520| ERR |  Thread-3/0383@sshtunnel | Could not establish connection from ('127.0.0.1', 8080) to remote side of the tunnel
2017-01-16 01:43:00,800| ERR |  Thread-1/1563@transport | Secsh channel 1 open FAILED: Connection refused: Connect failed
2017-01-16 01:43:00,800| TRA |  Thread-4/0344@sshtunnel | #2 <-- ('127.0.0.1', 56743) to ('127.0.0.1', 8080) was rejected by the SSH server
2017-01-16 01:43:00,800| ERR |  Thread-4/0383@sshtunnel | Could not establish connection from ('127.0.0.1', 8080) to remote side of the tunnel

```
Again, tried on various machines with various logins, which surely work elsewhere

**Comment by sambanks** [comment]
Same issue for me

**Comment by wzhan366** [comment]
I also got this issue

**Comment by Genyco** [comment]
I also got this issue

**Comment by fernandezcuesta** [comment]
Please refer to [Troubleshooting guidelines](https://github.com/pahaz/sshtunnel/blob/master/Troubleshoot.rst) to help isolating the root cause.

**Comment by Genyco** [comment]
I finally solved it.... a iptables issue, port 3306 not allowed

but....

iptables  -A INPUT -i eth0 -p tcp -m tcp --dport 3306 -j ACCEPT

made it

**Comment by eigen2017** [comment]
same issue for me:
2017-11-28 19:14:50,523| WAR | MainThrea/0954@sshtunnel | Could not read SSH configuration file: ~/.ssh/config
2017-11-28 19:14:50,524| INF | MainThrea/0981@sshtunnel | 0 keys loaded from agent
2017-11-28 19:14:50,524| INF | MainThrea/0901@sshtunnel | Connecting to gateway: 101.37.133.249:24102 as user 'root'
2017-11-28 19:14:50,525| DEB | MainThrea/0904@sshtunnel | Concurrent connections allowed: True
2017-11-28 19:14:50,525| DEB | MainThrea/1298@sshtunnel | Trying to log in with password: *************
2017-11-28 19:14:50,836| INF | Srv-58439/1318@sshtunnel | Opening tunnel: 127.0.0.1:58439 <> 192.169.3.212:10000
2017-11-28 19:14:51,839| TRA |  Thread-3/0344@sshtunnel | #1 <-- ('127.0.0.1', 46612) to ('192.169.3.212', 10000) was rejected by the SSH server
2017-11-28 19:14:51,839| ERR |  Thread-3/0383@sshtunnel | Could not establish connection from ('127.0.0.1', 58439) to remote side of the tunnel
2017-11-28 19:15:02,851| TRA |  Thread-4/0344@sshtunnel | #2 <-- ('127.0.0.1', 46614) to ('192.169.3.212', 10000) was rejected by the SSH server
2017-11-28 19:15:02,851| ERR |  Thread-4/0383@sshtunnel | Could not establish connection from ('127.0.0.1', 58439) to remote side of the tunnel
2017-11-28 19:15:13,864| TRA |  Thread-5/0344@sshtunnel | #3 <-- ('127.0.0.1', 46616) to ('192.169.3.212', 10000) was rejected by the SSH server

**Comment by eigen2017** [comment]
@Genyco i followd the command , output changed:

/usr/bin/python2.7 /home/code/PycharmProjects/heart_print_pure_lable/dbwrap.py
2017-11-28 19:18:44,544| WAR | MainThrea/0954@sshtunnel | Could not read SSH configuration file: ~/.ssh/config
2017-11-28 19:18:44,556| INF | MainThrea/0981@sshtunnel | 0 keys loaded from agent
2017-11-28 19:18:44,556| INF | MainThrea/0901@sshtunnel | Connecting to gateway: 101.37.133.249:24102 as user 'root'
2017-11-28 19:18:44,556| DEB | MainThrea/0904@sshtunnel | Concurrent connections allowed: True
2017-11-28 19:18:44,556| DEB | MainThrea/1298@sshtunnel | Trying to log in with password: *************
Traceback (most recent call last):
  File "/home/code/PycharmProjects/heart_print_pure_lable/dbwrap.py", line 38, in <module>
    a = dbwarap()
  File "/home/code/PycharmProjects/heart_print_pure_lable/dbwrap.py", line 26, in __init__
    self.server.start()
  File "/usr/lib/python2.7/site-packages/sshtunnel.py", line 1221, in start
    self._create_tunnels()
  File "/usr/lib/python2.7/site-packages/sshtunnel.py", line 1082, in _create_tunnels
    msg = 'Problem setting SSH Forwarder up: {0}'.format(e.args[0])
IndexError: tuple index out of range

**Comment by eigen2017** [comment]
my fault ! i gave a wrong
remote_bind_address

**Comment by kamalmeh** [comment]
Same issue for me.
Below are the errors.

2018-07-06 10:26:18,935| WAR | MainThrea/0967@sshtunnel | Could not read SSH configuration file: ~/.ssh/config
2018-07-06 10:26:18,936| INF | MainThrea/0993@sshtunnel | 0 keys loaded from agent
2018-07-06 10:26:18,936| INF | MainThrea/1042@sshtunnel | 0 keys loaded from host directory
2018-07-06 10:26:18,936| INF | MainThrea/0914@sshtunnel | Connecting to gateway: 216.104.205.89:22 as user 'admin'
2018-07-06 10:26:18,936| DEB | MainThrea/0917@sshtunnel | Concurrent connections allowed: True
2018-07-06 10:26:18,936| DEB | MainThrea/1369@sshtunnel | Trying to log in with password: *****
2018-07-06 10:26:23,156| INF | Srv-10000/1389@sshtunnel | Opening tunnel: 127.0.0.1:10000 <> 216.104.205.89:22
10000
2018-07-06 10:26:46,748| TRA |  Thread-3/0352@sshtunnel | #1 <-- ('127.0.0.1', 34564) connected
2018-07-06 10:26:46,749| TRA |  Thread-3/0315@sshtunnel | >>> OUT #1 <-- ('127.0.0.1', 34564) send to ('216.104.205.89', 22): 050100 >>>
2018-07-06 10:26:46,749| TRA |  Thread-3/0324@sshtunnel | <<< IN #1 <-- ('127.0.0.1', 34564) recv: 5353482d322e302d524f535353480d0a <<<
2018-07-06 10:26:46,750| TRA |  Thread-3/0360@sshtunnel | #1 <-- ('127.0.0.1', 34564) sending RST
2018-07-06 10:26:46,750| TRA |  Thread-3/0368@sshtunnel | #1 <-- ('127.0.0.1', 34564) connection closed.
2018-07-06 10:26:47,131| TRA |  Thread-4/0352@sshtunnel | #2 <-- ('127.0.0.1', 34568) connected
2018-07-06 10:26:47,132| TRA |  Thread-4/0315@sshtunnel | >>> OUT #2 <-- ('127.0.0.1', 34568) send to ('216.104.205.89', 22): 050100 >>>
2018-07-06 10:26:47,133| TRA |  Thread-4/0324@sshtunnel | <<< IN #2 <-- ('127.0.0.1', 34568) recv: 5353482d322e302d524f535353480d0a <<<
2018-07-06 10:26:47,133| TRA |  Thread-4/0360@sshtunnel | #2 <-- ('127.0.0.1', 34568) sending RST
2018-07-06 10:26:47,134| TRA |  Thread-4/0368@sshtunnel | #2 <-- ('127.0.0.1', 34568) connection closed.

Please help me urgently.
below is my program.

from sshtunnel import SSHTunnelForwarder, create_logger
import time

server = SSHTunnelForwarder(
    ('216.104.205.89',22),
    ssh_username="admin",
    ssh_password="admin",
    remote_bind_address=('216.104.205.89',22),
    local_bind_address=('127.0.0.1',10000),
    logger=create_logger(loglevel=1)
)

server.start()
print(server.local_bind_port)

**Comment by msramalho** [comment]
Had this issue on Docker and the problem was I wasn't exposing the port in my docker-compose.yml.

**Comment by HengyueLi** [comment]
Same issue, is there a "offical" solution?

**Comment by matteosdocsity** [comment]
> Had this issue on Docker and the problem was I wasn't exposing the port in my docker-compose.yml.

which port to be exposed in docker-compose.yml?

I'm experiencing the same problem and this is the error I receive:

` Could not establish connection from ('127.0.0.1', 33193) to remote side of the tunnel`

**Comment by dheeman00** [comment]
I am having this same issue. I have installed Mongodb using Docker on Synology DNS and I am trying to run a script from a server and the results will be stored into the disk. But I am unable to establish the connection.

import pymongo
from sshtunnel import SSHTunnelForwarder, create_logger

server = SSHTunnelForwarder(SSHKeys.REMOTE_IP_ADDRESS, ssh_username=SSHKeys.SSH_USERNAME,
                                            ssh_password=SSHKeys.SSH_PASSWD,
                                            remote_bind_address=('64.106.39.192', 22),
                                            local_bind_address=('127.0.0.1', 27017),
                                            logger=create_logger(loglevel=1))

                server.start()
                print(server.local_bind_port)
                client = pymongo.MongoClient('localhost', server.local_bind_port)
                client.server_info()

2020-08-13 11:13:33,258| WAR | MainThrea/0966@sshtunnel | Could not read SSH configuration file: ~/.ssh/config
2020-08-13 11:13:33,258| INF | MainThrea/0992@sshtunnel | 0 keys loaded from agent
2020-08-13 11:13:33,258| INF | MainThrea/1041@sshtunnel | 0 keys loaded from host directory
2020-08-13 11:13:33,259| INF | MainThrea/0913@sshtunnel | Connecting to gateway: 64.106.39.192:22 as user 'MueenLab'
2020-08-13 11:13:33,259| DEB | MainThrea/0916@sshtunnel | Concurrent connections allowed: True
2020-08-13 11:13:33,259| DEB | MainThrea/1368@sshtunnel | Trying to log in with password: **********
2020-08-13 11:13:33,488| ERR | MainThrea/1147@sshtunnel | Problem setting SSH Forwarder up: Couldn't open tunnel 127.0.0.1:27017 <> 64.106.39.192:22 might be in use or destination not reachable

**Comment by KeerthyDev** [comment]
Could anyone help with the below issue?
2021-02-26 00:26:13,932| WARNING | Could not read SSH configuration file: ~/.ssh/config
2021-02-26 00:26:13,935| INFO    | 0 keys loaded from agent
2021-02-26 00:26:13,991| DEBUG   | Private key file (/Users/keerthydevanand/.ssh/id_rsa, <class 'paramiko.rsakey.RSAKey'>) successfully loaded
2021-02-26 00:26:13,992| INFO    | 1 key(s) loaded
2021-02-26 00:26:14,019| DEBUG   | Private key file (/Users/keerthydevanand/Downloads/key.txt, <class 'paramiko.rsakey.RSAKey'>) successfully loaded
2021-02-26 00:26:14,019| INFO    | Connecting to gateway: xx.xx.xx.xx:22 as user 'xxxx'
2021-02-26 00:26:14,020| DEBUG   | Concurrent connections allowed: True
2021-02-26 00:26:14,021| DEBUG   | Trying to log in with key: b'f75c3c71c6303fd1e9e9efdd435c90ce'
2021-02-26 00:26:14,087| DEBUG   | Transport socket info: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0), timeout=0.1
2021-02-26 00:26:14,521| ERROR   | Problem setting SSH Forwarder up: Couldn't open tunnel 127.0.0.1:29221 <> xx.xx.xx.xx:xxxx might be in use or destination not reachable

**Comment by owenljn** [comment]
It's still giving me the same issue, is there a solution after 5 years?
